SKILL_CATALOG: dict[str, tuple[str, ...]] = {
    "python": ("py", "python3"),
    "java": ("java se",),
    "javascript": ("js",),
    "typescript": ("ts",),
    "react": ("react.js", "reactjs"),
    "node.js": ("node", "node js", "nodejs"),
    "sql": (),
    "nosql": ("no sql",),
    "aws": ("amazon web services", "amazon web service"),
    "cloud computing": ("cloud",),
    "docker": (),
    "kubernetes": ("k8s",),
    "terraform": (),
    "ci/cd": ("ci cd", "continuous integration", "continuous delivery", "continuous deployment"),
    "machine learning": ("ml",),
    "deep learning": ("neural network", "neural networks"),
    "data structures": ("data structure",),
    "algorithms": ("algorithm", "algorithmic"),
    "git": (),
    "linux": ("unix",),
    "embedded systems": ("embedded system", "embedded", "embedded development"),
    "arduino": (),
    "c": ("c programming", "ansi c"),
    "c++": ("c plus plus",),
    "vlsi": ("very large scale integration",),
    "verilog": (),
    "html": ("html5",),
    "css": ("css3",),
    "cybersecurity": ("cyber security", "information security", "infosec"),
    "networking": ("computer networking", "computer networks", "network programming"),
    "rest api": ("restful", "restful api", "restful apis"),
    "graphql": (),
    "postgresql": ("postgres", "postgre sql"),
    "mongodb": ("mongo",),
    "bash": ("shell scripting", "shell scripts"),
    "jenkins": (),
    "statistics": ("statistical analysis", "stats"),
    "tensorflow": ("tf",),
    "pytorch": ("torch",),
    "rust": (),
}
